name: certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      confs: ${{ steps.list.outputs.confs }}
    steps:
      - uses: actions/checkout@v4

      - id: list
        run: echo "confs=$(ls certora/confs/*.conf | xargs -I{} basename {} .conf | jq -nRc '[inputs]')" >> "$GITHUB_OUTPUT"

  verify:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        conf: ${{ fromJson(needs.matrix.outputs.confs) }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install Jq
        uses: sergeysova/jq-action@v2

      - name: Run Certora Config Linter
        run: |
          file="certora/confs/${{ matrix.conf }}.conf"
          echo "Fix lint errors by applying the following diff to $file:"
          diff -u "$file" <(jq < "$file")

      - uses: actions/setup-python@v5

      - name: Install certora
        run: pip install certora-cli

      - name: Run Certora Specs Linter
        run: |
          file="certora/specs/${{ matrix.conf }}.spec"
          echo "Fix lint errors by applying the following diff to $file:"
          diff -u "$file" <(certoraCVLFormatter "$file")

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install solc 0.8.34
        run: |
          mkdir -p ~/.svm/0.8.34
          curl -L --retry 3 --retry-all-errors \
            https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.34+commit.80d5c536 \
            -o ~/.svm/0.8.34/solc-0.8.34
          chmod +x ~/.svm/0.8.34/solc-0.8.34
          cp ~/.svm/0.8.34/solc-0.8.34 /usr/local/bin
          forge build

      - name: Verify ${{ matrix.conf }}
        run: certoraRun certora/confs/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
